### ISSUE TITLE
Bug in new log naming or execution

### ISSUE THREAD

**Issue by balis** [hyperflow-wms/hyperflow-job-executor#10]
I ran a small Montage on 1 node and some tasks have failed with the following output:
```
Job executor will execute tasks: SBk1CTHAu:1:2:1
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/work_dir/logs-hf/task-SBk1CTHAu__1__2__1@KOLX718GG__stdout.log'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/work_dir/logs-hf/task-SBk1CTHAu__1__2__1@KOLX718GG__stdout.log'
}
Command hflow-job-execute redis://redis.default.svc.cluster.local:6379 -a SBk1CTHAu:1:2:1 returned exit code. 1. Job fails.
```

Here's output of `ls -l *__1__2__*`:
```
/work_dir/logs-hf # ls -l *__1__2__*
-rw-r--r--    1 root     root             0 Oct 16 11:44 task-SBk1CTHAu__1__2__1@KOLX718GG.log
-rw-r--r--    1 root     root          3401 Oct 16 11:44 task-SBk1CTHAu__1__2__1@h3W-vLZ3v.log
-rw-r--r--    1 root     root            23 Oct 16 11:44 task-SBk1CTHAu__1__2__1@h3W-vLZ3v__nethogs.log
-rw-r--r--    1 root     root             0 Oct 16 11:44 task-SBk1CTHAu__1__2__1@h3W-vLZ3v__stderr.log
-rw-r--r--    1 root     root            27 Oct 16 11:44 task-SBk1CTHAu__1__2__1@h3W-vLZ3v__stdout.log
```

Why would `task-SBk1CTHAu__1__2__1@KOLX718GG.log` have 0 size?

It looks like restart of task `SBk1CTHAu:1:2:1` but log `task-SBk1CTHAu__1__2__1@h3W-vLZ3v.log` indicates that job was succesful:
```
/work_dir/logs-hf # cat  task-SBk1CTHAu__1__2__1@h3W-vLZ3v.log
[2020-10-16T11:44:05.156] [INFO] hftrace - Environment variables (HF_LOG): {"podIp":"10.52.1.17","nodeName":"gke-hf-cluster-worker-nodes-63e31d05-91tc","podName":"job89rl4t-mprojectpp-2-1-dx7lk","podServiceAccount":"default","podNamespace":"default"}
[2020-10-16T11:44:05.157] [INFO] hftrace - handler started, (ID: h3W-vLZ3v)
[2020-10-16T11:44:05.163] [INFO] hftrace - jobMessage:  {"executable":"mProjectPP","args":["-X","-x","0.90274","2mass-atlas-001124n-j0890232.fits","p2mass-atlas-001124n-j0890232.fits","big_region_20180402_165339_22325.hdr"],"inputs":[{"name":"big_region_20180402_165339_22325.hdr","_id":4,"data":[{}],"sigIdx":1},{"name":"2mass-atlas-001124n-j0890232.fits","_id":5,"data":[{}],"sigIdx":1}],"outputs":[{"name":"p2mass-atlas-001124n-j0890232.fits"},{"name":"p2mass-atlas-001124n-j0890232_area.fits"}],"redis_url":"redis://redis.default.svc.cluster.local:6379","taskId":"SBk1CTHAu:1:2:1","name":"mProjectPP"}
[2020-10-16T11:44:05.170] [INFO] hftrace - Job command: 'mProjectPP -X -x 0.90274 2mass-atlas-001124n-j0890232.fits p2mass-atlas-001124n-j0890232.fits big_region_20180402_165339_22325.hdr'
[2020-10-16T11:44:05.176] [INFO] hftrace - command: {"pid":18,"name":"mProjectPP","command":["mProjectPP","-X","-x","0.90274","2mass-atlas-001124n-j0890232.fits","p2mass-atlas-001124n-j0890232.fits","big_region_20180402_165339_22325.hdr"]}
[2020-10-16T11:44:05.177] [INFO] hftrace - IO: {"read":69838,"write":1,"readSyscalls":10,"writeSyscalls":1,"readReal":921600,"writeReal":0,"writeCancelled":0,"pid":18,"name":"mProjectPP"}
[2020-10-16T11:44:05.179] [INFO] hftrace - NetDev: pid: 18 [{"name":"lo","rxBytes":0,"rxPackets":0,"rxErrors":0,"rxDrop":0,"rxFifo":0,"rxFrame":0,"rxCompressed":0,"rxMulticast":0,"txBytes":0,"txPackets":0,"txErrors":0,"txDrop":0,"txFifo":0,"txColls":0,"txCarrier":0,"txCompressed":0},{"name":"eth0","rxBytes":5901,"rxPackets":17,"rxErrors":0,"rxDrop":0,"rxFifo":0,"rxFrame":0,"rxCompressed":0,"rxMulticast":0,"txBytes":1790,"txPackets":18,"txErrors":0,"txDrop":0,"txFifo":0,"txColls":0,"txCarrier":0,"txCompressed":0}]
[2020-10-16T11:44:05.187] [INFO] hftrace - job started: mProjectPP
[2020-10-16T11:44:05.215] [INFO] hftrace - Procusage: pid: 18 {"cpu":0,"memory":2674688,"ctime":30,"elapsed":30,"timestamp":1602848645215,"pid":18,"ppid":6}
[2020-10-16T11:44:05.216] [INFO] hftrace - Sysinfo: {"cpu":{"manufacturer":"Intel®","brand":"Xeon®","vendor":"GenuineIntel","family":"6","model":"79","stepping":"0","revision":"","voltage":"","speed":"2.20","speedmin":"","speedmax":"","governor":"","cores":8,"physicalCores":4,"processors":1,"socket":"","cache":{"l1d":32768,"l1i":32768,"l2":262144,"l3":57671680}},"mem":{"total":67557625856,"free":64861954048,"used":2695671808,"active":1581277184,"available":65976348672,"buffers":60452864,"cached":1495388160,"slab":288370688,"buffcache":1844211712,"swaptotal":0,"swapused":0,"swapfree":0}}
[2020-10-16T11:44:05.955] [INFO] hftrace - job successful (try 1): mProjectPP
[2020-10-16T11:44:05.956] [INFO] hftrace - job exit code: 0
[2020-10-16T11:44:05.958] [INFO] hftrace - Job inputs: [{"big_region_20180402_165339_22325.hdr":306},{"2mass-atlas-001124n-j0890232.fits":1604128}]
[2020-10-16T11:44:05.958] [INFO] hftrace - Job outputs: [{"p2mass-atlas-001124n-j0890232.fits":4124160},{"p2mass-atlas-001124n-j0890232_area.fits":4124160}]
[2020-10-16T11:44:05.958] [INFO] hftrace - handler finished, code= 0
```

**Comment by balis** [comment]
Update: executor processes never finish, it could be because `ENABLE_NETHOGS=1` (executor spawns `nethogs-wrapper.py`). But does it explain the error above?

**Comment by balis** [comment]
Full time output:
```
-rw-r--r--    1 root     root             0 2020-10-16 11:44:01 +0000 task-SBk1CTHAu__1__2__1@KOLX718GG.log
-rw-r--r--    1 root     root          3401 2020-10-16 11:44:05 +0000 task-SBk1CTHAu__1__2__1@h3W-vLZ3v.log
-rw-r--r--    1 root     root            23 2020-10-16 11:44:06 +0000 task-SBk1CTHAu__1__2__1@h3W-vLZ3v__nethogs.log
-rw-r--r--    1 root     root             0 2020-10-16 11:44:05 +0000 task-SBk1CTHAu__1__2__1@h3W-vLZ3v__stderr.log
-rw-r--r--    1 root     root            27 2020-10-16 11:44:05 +0000 task-SBk1CTHAu__1__2__1@h3W-vLZ3v__stdout.log
```

**Comment by koxu1996** [comment]
Restarting tasks was hunting us for a long time, but finally nailed it: the log directory doesn't exist during first run, so there is _ENOENT_, but `log4js` creates it in the meantime, so second restart is successful.

Code for reproducing issue:
```
const fs = require('fs');
const log4js = require('log4js');

fs.createWriteStream('./logs/1.log', {flags: 'w'});

log4js.configure({
  appenders: { hftrace: { type: 'file', filename: './logs/1__stdout.log'} },
  categories: { default: { appenders: ['hftrace'], level: 'info' } }
});

const logger = log4js.getLogger('hftrace');

```
First execution:
```
$ node log.js    
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open './logs/1.log'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:375:14
    at FSReqCallback.oncomplete (fs.js:169:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './logs/1.log'
}
$ // We got ENOENT erro because there was no `logs` directory
```
Second attempt:
```
$ node log.js
$ // OK!
```
